### ISSUE TITLE
bug i requirement 16

### ISSUE THREAD

**Issue by aatjora** [kartverket/SOSIModelValidationAddIn#38]
Oppdaget ved kjøring av test på Areal-4.0
Ser ut som om feil ligger i requirement16onConnectorEnd.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMemberException: Public member 'ConnectorID' on type 'IDualConnectorEnd' not found.
   at Microsoft.VisualBasic.CompilerServices.LateBinding.LateGet(Object o, Type objType, String name, Object[] args, String[] paramnames, Boolean[] CopyBack)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack)
   at SOSIModelValidation.ModelValidation.requirement16onConnectorEnd(Object theConnectorEnd) in C:\s\GitHub\SOSIModelValidationAddIn\SOSIModelValidation\requirement16.vb:line 128
   at SOSIModelValidation.ModelValidation.requirement16(ConnectorEnd theThing) in C:\s\GitHub\SOSIModelValidationAddIn\SOSIModelValidation\requirement16.vb:line 28
   at SOSIModelValidation.ModelValidation.FindInvalidElementsInPackage(Package thePackage) in C:\s\GitHub\SOSIModelValidationAddIn\SOSIModelValidation\ModelValidation.vb:line 296
   at SOSIModelValidation.ModelValidation.FindInvalidElementsInPackage(Package thePackage) in C:\s\GitHub\SOSIModelValidationAddIn\SOSIModelValidation\ModelValidation.vb:line 208
   at SOSIModelValidation.ModelValidation.RunValidation() in C:\s\GitHub\SOSIModelValidationAddIn\SOSIModelValidation\ModelValidation.vb:line 158
   at SOSIModelValidation.SOSIModelValidationWindow.ButtonRun_Click(Object sender, EventArgs e) in C:\s\GitHub\SOSIModelValidationAddIn\SOSIModelValidation\SOSIModelValidationWindow.vb:line 31
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Arkitektum.Statkart.ShapeChange.EA.Addin
    Assembly Version: 1.0.0.2
    Win32 Version: 1.0.0.2
    CodeBase: file:///C:/Program%20Files%20(x86)/Arkitektum%20AS/ShapeChange/Arkitektum.Statkart.ShapeChange.EA.Addin.dll
----------------------------------------
Arkitektum.Kartverket.SOSI.EA.Plugin
    Assembly Version: 1.14.0.0
    Win32 Version: 1.14.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Arkitektum%20AS/SOSI/Arkitektum.Kartverket.SOSI.EA.Plugin.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SOSIModelValidation
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/LocalGit/SOSIModelValidationAddIn/SOSIModelValidation/bin/Debug/SOSIModelValidation.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Arkitektum.Kartverket.SOSI.Model
    Assembly Version: 1.14.0.0
    Win32 Version: 1.14.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Arkitektum%20AS/SOSI/Arkitektum.Kartverket.SOSI.Model.DLL
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by magnusKarge** [comment]
fixed in #61
